<a href="https://colab.research.google.com/github/RonGopal/intro_to_AI/blob/main/FinalProjectPt2rrg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import datetime as dt
from sklearn.preprocessing import OneHotEncoder
import csv

In [24]:
hsp = pd.read_csv('historical_stock_prices.csv')
hs = pd.read_csv('historical_stocks.csv')

In [25]:
display(hsp.shape)
print()
display(hs.shape)

(20973889, 8)

(6460, 5)

In [26]:
#remove obvious header row
hs = hs[hs['ticker'] !='Symbol'].copy()

In [27]:
# convert date column to datetime type
hsp['date'] = pd.to_datetime(hsp['date'])

In [28]:
#sort price data
hsp = hsp.sort_values(['ticker', 'date'])

In [29]:
df = hsp

df['price_change'] = df['close'].diff()
df['daily_return'] = df.groupby('ticker')['close'].pct_change()
df['close_lag_1'] = df.groupby('ticker')['close'].shift(1)

df['ma5'] = (
    df.groupby('ticker')['close']
    .transform(lambda x: x.rolling(5).mean())
)

df['ma20'] = (
    df.groupby('ticker')['close']
    .transform(lambda x: x.rolling(20).mean())
)

In [30]:
df.head()

,ticker,open,close,adj_close,low,high,volume,date,price_change,daily_return,close_lag_1,ma5,ma20
13766141,A,32.546494,31.473534,27.494957,28.612303,35.765381,62546300,1999-11-18,NaN,NaN,NaN,NaN,NaN
13766149,A,30.713520,28.880543,25.229753,28.478184,30.758226,15234100,1999-11-19,-2.592991,-0.082386,31.473534,NaN,NaN
13766150,A,29.551144,31.473534,27.494957,28.657009,31.473534,6577800,1999-11-22,2.592991,0.089783,28.880543,NaN,NaN
13766151,A,30.400572,28.612303,24.995413,28.612303,31.205294,5975600,1999-11-23,-2.861231,-0.090909,31.473534,NaN,NaN
13766152,A,28.701717,29.372318,25.659359,28.612303,29.998211,4843200,1999-11-24,0.760015,0.026563,28.612303,29.962446,NaN

In [31]:
df['volatility_20'] = (
    df.groupby('ticker')['daily_return']
    .transform(lambda x: x.rolling(20).std())
)

In [32]:
df.head(30)

,ticker,open,close,adj_close,low,high,volume,date,price_change,daily_return,close_lag_1,ma5,ma20,volatility_20
13766141,A,32.546494,31.473534,27.494957,28.612303,35.765381,62546300,1999-11-18,NaN,NaN,NaN,NaN,NaN,NaN
13766149,A,30.713520,28.880543,25.229753,28.478184,30.758226,15234100,1999-11-19,-2.592991,-0.082386,31.473534,NaN,NaN,NaN
13766150,A,29.551144,31.473534,27.494957,28.657009,31.473534,6577800,1999-11-22,2.592991,0.089783,28.880543,NaN,NaN,NaN
13766151,A,30.400572,28.612303,24.995413,28.612303,31.205294,5975600,1999-11-23,-2.861231,-0.090909,31.473534,NaN,NaN,NaN
13766152,A,28.701717,29.372318,25.659359,28.612303,29.998211,4843200,1999-11-24,0.760015,0.026563,28.612303,29.962446,NaN,NaN
13766153,A,29.238197,29.461731,25.737471,29.148785,29.685265,1729400,1999-11-26,0.089413,0.003044,29.372318,29.560086,NaN,NaN
13766154,A,29.327610,30.132332,26.323301,29.014664,30.355865,4074700,1999-11-29,0.670601,0.022762,29.461731,29.810443,NaN,NaN
13766155,A,30.042919,30.177038,26.362358,29.282904,30.713520,4310000,1999-11-30,0.044706,0.001484,30.132332,29.551144,NaN,NaN
13766156,A,30.177038,30.713520,26.831017,29.953505,31.071173,2957300,1999-12-01,0.536482,0.017778,30.177038,29.971388,NaN,NaN
13766157,A,31.294706,31.562946,27.573071,30.892345,32.188843,3069800,1999-12-02,0.849426,0.027656,30.713520,30.409513,NaN,NaN
13766158,A,32.144135,31.831188,27.807402,31.697067,32.680614,3041600,1999-12-03,0.268242,0.008499,31.562946,30.883405,NaN,NaN
13766159,A,32.367668,32.725323,28.588512,32.322960,33.217094,2250700,1999-12-06,0.894135,0.028090,31.831188,31.402003,NaN,NaN
13766160,A,32.725323,32.367668,28.276072,31.697067,32.904148,2215900,1999-12-07,-0.357655,-0.010929,32.725323,31.840129,NaN,NaN
13766161,A,32.367668,32.322960,28.237005,32.054722,32.635910,1887800,1999-12-08,-0.044708,-0.001381,32.367668,32.162017,NaN,NaN
13766162,A,32.367668,32.770027,28.627558,32.367668,32.859444,2029000,1999-12-09,0.447067,0.013831,32.322960,32.403433,NaN,NaN
13766163,A,32.680614,32.010014,27.963623,32.010014,32.859444,1664700,1999-12-10,-0.760014,-0.023192,32.770027,32.439198,NaN,NaN
13766164,A,32.546494,32.546494,28.432285,31.741774,33.082977,4020500,1999-12-13,0.536480,0.016760,32.010014,32.403432,NaN,NaN
13766165,A,32.457081,30.758226,26.870071,30.087626,32.457081,2328900,1999-12-14,-1.788267,-0.054945,32.546494,32.081544,NaN,NaN
13766175,A,30.042919,29.819386,26.049913,29.327610,30.266453,2917700,1999-12-15,-0.938841,-0.030523,30.758226,31.580829,NaN,NaN
13766176,A,30.042919,33.798283,29.525833,30.042919,33.798283,2583900,1999-12-16,3.978897,0.133433,29.819386,31.786480,31.140468,NaN
13766177,A,33.172390,32.859444,28.705677,32.501789,33.708870,3708000,1999-12-17,-0.938839,-0.027778,33.798283,31.956366,31.209764,0.051155
13766178,A,33.082977,33.530045,29.291510,32.993561,33.574749,1196800,1999-12-20,0.670601,0.020408,32.859444,32.153077,31.442239,0.047086
13766179,A,33.395924,33.351215,29.135279,32.904148,33.395924,2259400,1999-12-21,-0.178829,-0.005333,33.530045,32.671674,31.536123,0.043080
13766180,A,33.351215,34.021816,29.721119,33.127682,34.021816,1905700,1999-12-22,0.670601,0.020107,33.351215,33.512160,31.806599,0.036956
13766181,A,33.977112,35.586552,31.088053,33.932404,35.765381,2159400,1999-12-23,1.564735,0.045992,34.021816,33.869814,32.117310,0.037681
13766189,A,35.720673,37.777184,33.001759,35.452431,38.045422,2029600,1999-12-27,2.190632,0.061558,35.586552,34.853362,32.533083,0.039325
13766190,A,38.805435,43.991417,38.430462,38.581902,43.991417,3560000,1999-12-28,6.214233,0.164497,37.777184,36.945637,33.226037,0.051897
13766191,A,45.064377,51.502148,44.991753,45.019672,56.554005,10518500,1999-12-29,7.510731,0.170732,43.991417,40.575823,34.292293,0.061566
13766192,A,54.363377,56.688126,49.522171,53.111588,57.224606,6671100,1999-12-30,5.185978,0.100694,51.502148,45.109085,35.591023,0.063547
13766193,A,56.866951,55.302216,48.311455,54.542202,57.179901,1931100,1999-12-31,-1.385910,-0.024448,56.688126,49.052218,36.777986,0.064829

In [33]:
# Daily price range, how much stock moved in a day

df['daily_range_pct'] = ((df['high'] - df['low']) / df['close'] * 100)

In [34]:
df[['ticker', 'date', 'close',
    'price_change', 'daily_return',
    'close_lag_1', 'ma5', 'ma20',
    'volatility_20', 'daily_range_pct']].head(25)

,ticker,date,close,price_change,daily_return,close_lag_1,ma5,ma20,volatility_20,daily_range_pct
13766141,A,1999-11-18,31.473534,NaN,NaN,NaN,NaN,NaN,NaN,22.727280
13766149,A,1999-11-19,28.880543,-2.592991,-0.082386,31.473534,NaN,NaN,NaN,7.894736
13766150,A,1999-11-22,31.473534,2.592991,0.089783,28.880543,NaN,NaN,NaN,8.948866
13766151,A,1999-11-23,28.612303,-2.861231,-0.090909,31.473534,NaN,NaN,NaN,9.062503
13766152,A,1999-11-24,29.372318,0.760015,0.026563,28.612303,29.962446,NaN,NaN,4.718416
13766153,A,1999-11-26,29.461731,0.089413,0.003044,29.372318,29.560086,NaN,NaN,1.820938
13766154,A,1999-11-29,30.132332,0.670601,0.022762,29.461731,29.810443,NaN,NaN,4.451039
13766155,A,1999-11-30,30.177038,0.044706,0.001484,30.132332,29.551144,NaN,NaN,4.740745
13766156,A,1999-12-01,30.713520,0.536482,0.017778,30.177038,29.971388,NaN,NaN,3.639010
13766157,A,1999-12-02,31.562946,0.849426,0.027656,30.713520,30.409513,NaN,NaN,4.107656
13766158,A,1999-12-03,31.831188,0.268242,0.008499,31.562946,30.883405,NaN,NaN,3.089885
13766159,A,1999-12-06,32.725323,0.894135,0.028090,31.831188,31.402003,NaN,NaN,2.732241
13766160,A,1999-12-07,32.367668,-0.357655,-0.010929,32.725323,31.840129,NaN,NaN,3.729280
13766161,A,1999-12-08,32.322960,-0.044708,-0.001381,32.367668,32.162017,NaN,NaN,1.798066
13766162,A,1999-12-09,32.770027,0.447067,0.013831,32.322960,32.403433,NaN,NaN,1.500687
13766163,A,1999-12-10,32.010014,-0.760014,-0.023192,32.770027,32.439198,NaN,NaN,2.653639
13766164,A,1999-12-13,32.546494,0.536480,0.016760,32.010014,32.403432,NaN,NaN,4.120885
13766165,A,1999-12-14,30.758226,-1.788267,-0.054945,32.546494,32.081544,NaN,NaN,7.703485
13766175,A,1999-12-15,29.819386,-0.938841,-0.030523,30.758226,31.580829,NaN,NaN,3.148431
13766176,A,1999-12-16,33.798283,3.978897,0.133433,29.819386,31.786480,31.140468,NaN,11.111107
13766177,A,1999-12-17,32.859444,-0.938839,-0.027778,33.798283,31.956366,31.209764,0.051155,3.673467
13766178,A,1999-12-20,33.530045,0.670601,0.020408,32.859444,32.153077,31.442239,0.047086,1.733336
13766179,A,1999-12-21,33.351215,-0.178829,-0.005333,33.530045,32.671674,31.536123,0.043080,1.474536
13766180,A,1999-12-22,34.021816,0.670601,0.020107,33.351215,33.512160,31.806599,0.036956,2.628121
13766181,A,1999-12-23,35.586552,1.564735,0.045992,34.021816,33.869814,32.117310,0.037681,5.150758

In [35]:
metadata = hs[[
    'ticker', 'exchange', 'sector', 'industry'
]]

In [36]:
df = df.merge(
    metadata, how='left', on='ticker'
)

In [37]:
df['sector'].value_counts()

sector
FINANCE                  3134211
CONSUMER SERVICES        2860951
TECHNOLOGY               2254333
HEALTH CARE              2093693
CAPITAL GOODS            1882123
BASIC INDUSTRIES         1260118
PUBLIC UTILITIES         1136093
ENERGY                   1101558
CONSUMER NON-DURABLES    1083387
CONSUMER DURABLES         710729
MISCELLANEOUS             488907
TRANSPORTATION            418337
Name: count, dtype: int64

In [38]:
df.head(20)

,ticker,open,close,adj_close,low,high,volume,date,price_change,daily_return,close_lag_1,ma5,ma20,volatility_20,daily_range_pct,exchange,sector,industry
0,A,32.546494,31.473534,27.494957,28.612303,35.765381,62546300,1999-11-18,NaN,NaN,NaN,NaN,NaN,NaN,22.727280,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
1,A,30.713520,28.880543,25.229753,28.478184,30.758226,15234100,1999-11-19,-2.592991,-0.082386,31.473534,NaN,NaN,NaN,7.894736,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
2,A,29.551144,31.473534,27.494957,28.657009,31.473534,6577800,1999-11-22,2.592991,0.089783,28.880543,NaN,NaN,NaN,8.948866,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
3,A,30.400572,28.612303,24.995413,28.612303,31.205294,5975600,1999-11-23,-2.861231,-0.090909,31.473534,NaN,NaN,NaN,9.062503,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
4,A,28.701717,29.372318,25.659359,28.612303,29.998211,4843200,1999-11-24,0.760015,0.026563,28.612303,29.962446,NaN,NaN,4.718416,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
5,A,29.238197,29.461731,25.737471,29.148785,29.685265,1729400,1999-11-26,0.089413,0.003044,29.372318,29.560086,NaN,NaN,1.820938,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
6,A,29.327610,30.132332,26.323301,29.014664,30.355865,4074700,1999-11-29,0.670601,0.022762,29.461731,29.810443,NaN,NaN,4.451039,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
7,A,30.042919,30.177038,26.362358,29.282904,30.713520,4310000,1999-11-30,0.044706,0.001484,30.132332,29.551144,NaN,NaN,4.740745,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
8,A,30.177038,30.713520,26.831017,29.953505,31.071173,2957300,1999-12-01,0.536482,0.017778,30.177038,29.971388,NaN,NaN,3.639010,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
9,A,31.294706,31.562946,27.573071,30.892345,32.188843,3069800,1999-12-02,0.849426,0.027656,30.713520,30.409513,NaN,NaN,4.107656,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
10,A,32.144135,31.831188,27.807402,31.697067,32.680614,3041600,1999-12-03,0.268242,0.008499,31.562946,30.883405,NaN,NaN,3.089885,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
11,A,32.367668,32.725323,28.588512,32.322960,33.217094,2250700,1999-12-06,0.894135,0.028090,31.831188,31.402003,NaN,NaN,2.732241,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
12,A,32.725323,32.367668,28.276072,31.697067,32.904148,2215900,1999-12-07,-0.357655,-0.010929,32.725323,31.840129,NaN,NaN,3.729280,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
13,A,32.367668,32.322960,28.237005,32.054722,32.635910,1887800,1999-12-08,-0.044708,-0.001381,32.367668,32.162017,NaN,NaN,1.798066,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
14,A,32.367668,32.770027,28.627558,32.367668,32.859444,2029000,1999-12-09,0.447067,0.013831,32.322960,32.403433,NaN,NaN,1.500687,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
15,A,32.680614,32.010014,27.963623,32.010014,32.859444,1664700,1999-12-10,-0.760014,-0.023192,32.770027,32.439198,NaN,NaN,2.653639,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
16,A,32.546494,32.546494,28.432285,31.741774,33.082977,4020500,1999-12-13,0.536480,0.016760,32.010014,32.403432,NaN,NaN,4.120885,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
17,A,32.457081,30.758226,26.870071,30.087626,32.457081,2328900,1999-12-14,-1.788267,-0.054945,32.546494,32.081544,NaN,NaN,7.703485,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
18,A,30.042919,29.819386,26.049913,29.327610,30.266453,2917700,1999-12-15,-0.938841,-0.030523,30.758226,31.580829,NaN,NaN,3.148431,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS
19,A,30.042919,33.798283,29.525833,30.042919,33.798283,2583900,1999-12-16,3.978897,0.133433,29.819386,31.786480,31.140468,NaN,11.111107,NYSE,CAPITAL GOODS,BIOTECHNOLOGY: LABORATORY ANALYTICAL INSTRUMENTS

In [39]:
df[['daily_return', 'close_lag_1', 'ma5', 'ma20', 'volatility_20']].isna().sum()

daily_return       5685
close_lag_1        5685
ma5               22735
ma20             107884
volatility_20    113555
dtype: int64

In [40]:
df = df.dropna(
    subset=['daily_return', 'close_lag_1', 'ma5', 'ma20', 'volatility_20']
)

In [41]:
df.isna().sum()

ticker                   0
open                     0
close                    0
adj_close                0
low                      0
high                     0
volume                   0
date                     0
price_change             0
daily_return             0
close_lag_1              0
ma5                      0
ma20                     0
volatility_20            0
daily_range_pct          0
exchange                 0
sector             2531217
industry           2531217
dtype: int64

In [42]:
# One-hot encode 'exchange'
exchange_encoder = OneHotEncoder(sparse_output=False)
encoded_exchange = exchange_encoder.fit_transform(df[['exchange']])
exchange_df = pd.DataFrame(encoded_exchange, columns=exchange_encoder.get_feature_names_out(['exchange']), index=df.index)
df = pd.concat([df, exchange_df], axis=1).drop(columns=['exchange'])

# One-hot encode 'sector'
sector_encoder = OneHotEncoder(sparse_output=False)
encoded_sector = sector_encoder.fit_transform(df[['sector']])
sector_df = pd.DataFrame(encoded_sector, columns=sector_encoder.get_feature_names_out(['sector']), index=df.index)
df = pd.concat([df, sector_df], axis=1).drop(columns=['sector'])

In [43]:
df.to_csv('stock_prepared.csv', index=False)